In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Q.Perform Clustering(Hierarchical, Kmeans & DBSCAN) for the crime data and identify the number of clusters formed and draw inferences.

In [3]:
db = pd.read_csv('crime_data.csv')
db

Unnamed: 0  Murder  Assault  UrbanPop  Rape
0          Alabama    13.2      236        58  21.2
1           Alaska    10.0      263        48  44.5
2          Arizona     8.1      294        80  31.0
3         Arkansas     8.8      190        50  19.5
4       California     9.0      276        91  40.6
5         Colorado     7.9      204        78  38.7
6      Connecticut     3.3      110        77  11.1
7         Delaware     5.9      238        72  15.8
8          Florida    15.4      335        80  31.9
9          Georgia    17.4      211        60  25.8
10          Hawaii     5.3       46        83  20.2
11           Idaho     2.6      120        54  14.2
12        Illinois    10.4      249        83  24.0
13         Indiana     7.2      113        65  21.0
14            Iowa     2.2       56        57  11.3
15          Kansas     6.0      115        66  18.0
16        Kentucky     9.7      109        52  16.3
17       Louisiana    15.4      249        66  22.2
18           Maine     2.1       83        51   7.8
19        Maryland    11.3      300        67  27.8
20   Massachusetts     4.4      149        85  16.3
21        Michigan    12.1      255        74  35.1
22       Minnesota     2.7       72        66  14.9
23     Mississippi    16.1      259        44  17.1
24        Missouri     9.0      178        70  28.2
25         Montana     6.0      109        53  16.4
26        Nebraska     4.3      102        62  16.5
27          Nevada    12.2      252        81  46.0
28   New Hampshire     2.1       57        56   9.5
29      New Jersey     7.4      159        89  18.8
30      New Mexico    11.4      285        70  32.1
31        New York    11.1      254        86  26.1
32  North Carolina    13.0      337        45  16.1
33    North Dakota     0.8       45        44   7.3
34            Ohio     7.3      120        75  21.4
35        Oklahoma     6.6      151        68  20.0
36          Oregon     4.9      159        67  29.3
37    Pennsylvania     6.3      106        72  14.9
38    Rhode Island     3.4      174        87   8.3
39  South Carolina    14.4      279        48  22.5
40    South Dakota     3.8       86        45  12.8
41       Tennessee    13.2      188        59  26.9
42           Texas    12.7      201        80  25.5
43            Utah     3.2      120        80  22.9
44         Vermont     2.2       48        32  11.2
45        Virginia     8.5      156        63  20.7
46      Washington     4.0      145        73  26.2
47   West Virginia     5.7       81        39   9.3
48       Wisconsin     2.6       53        66  10.8
49         Wyoming     6.8      161        60  15.6

In [4]:
db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  50 non-null     object 
 1   Murder      50 non-null     float64
 2   Assault     50 non-null     int64  
 3   UrbanPop    50 non-null     int64  
 4   Rape        50 non-null     float64
dtypes: float64(2), int64(2), object(1)
memory usage: 2.1+ KB


In [5]:
db.describe()

Murder     Assault   UrbanPop       Rape
count  50.00000   50.000000  50.000000  50.000000
mean    7.78800  170.760000  65.540000  21.232000
std     4.35551   83.337661  14.474763   9.366385
min     0.80000   45.000000  32.000000   7.300000
25%     4.07500  109.000000  54.500000  15.075000
50%     7.25000  159.000000  66.000000  20.100000
75%    11.25000  249.000000  77.750000  26.175000
max    17.40000  337.000000  91.000000  46.000000

In [6]:
def norm_func(i):
    x=(i-i.min())/(i.max()-i.min())
    return(x)

In [8]:
db_norm=norm_func(db.iloc[:,1:])
db_norm

Murder   Assault  UrbanPop      Rape
0   0.746988  0.654110  0.440678  0.359173
1   0.554217  0.746575  0.271186  0.961240
2   0.439759  0.852740  0.813559  0.612403
3   0.481928  0.496575  0.305085  0.315245
4   0.493976  0.791096  1.000000  0.860465
5   0.427711  0.544521  0.779661  0.811370
6   0.150602  0.222603  0.762712  0.098191
7   0.307229  0.660959  0.677966  0.219638
8   0.879518  0.993151  0.813559  0.635659
9   1.000000  0.568493  0.474576  0.478036
10  0.271084  0.003425  0.864407  0.333333
11  0.108434  0.256849  0.372881  0.178295
12  0.578313  0.698630  0.864407  0.431525
13  0.385542  0.232877  0.559322  0.354005
14  0.084337  0.037671  0.423729  0.103359
15  0.313253  0.239726  0.576271  0.276486
16  0.536145  0.219178  0.338983  0.232558
17  0.879518  0.698630  0.576271  0.385013
18  0.078313  0.130137  0.322034  0.012920
19  0.632530  0.873288  0.593220  0.529716
20  0.216867  0.356164  0.898305  0.232558
21  0.680723  0.719178  0.711864  0.718346
22  0.114458  0.092466  0.576271  0.196382
23  0.921687  0.732877  0.203390  0.253230
24  0.493976  0.455479  0.644068  0.540052
25  0.313253  0.219178  0.355932  0.235142
26  0.210843  0.195205  0.508475  0.237726
27  0.686747  0.708904  0.830508  1.000000
28  0.078313  0.041096  0.406780  0.056848
29  0.397590  0.390411  0.966102  0.297158
30  0.638554  0.821918  0.644068  0.640827
31  0.620482  0.715753  0.915254  0.485788
32  0.734940  1.000000  0.220339  0.227390
33  0.000000  0.000000  0.203390  0.000000
34  0.391566  0.256849  0.728814  0.364341
35  0.349398  0.363014  0.610169  0.328165
36  0.246988  0.390411  0.593220  0.568475
37  0.331325  0.208904  0.677966  0.196382
38  0.156627  0.441781  0.932203  0.025840
39  0.819277  0.801370  0.271186  0.392765
40  0.180723  0.140411  0.220339  0.142119
41  0.746988  0.489726  0.457627  0.506460
42  0.716867  0.534247  0.813559  0.470284
43  0.144578  0.256849  0.813559  0.403101
44  0.084337  0.010274  0.000000  0.100775
45  0.463855  0.380137  0.525424  0.346253
46  0.192771  0.342466  0.694915  0.488372
47  0.295181  0.123288  0.118644  0.051680
48  0.108434  0.027397  0.576271  0.090439
49  0.361446  0.397260  0.474576  0.214470

In [10]:
import scipy.cluster.hierarchy as sch

In [12]:
dendrogram=sch.dendrogram(sch.linkage(db_norm,method='average'))

In [14]:
from sklearn.cluster import AgglomerativeClustering

In [15]:
hc=AgglomerativeClustering(n_clusters=3,affinity='euclidean',linkage='complete')
hc

AgglomerativeClustering(linkage='complete', n_clusters=3)

In [17]:
y_hc=hc.fit_predict(db_norm)
y_hc

array([0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 2, 0, 1, 2, 1, 1, 0, 2, 0, 1, 0,
       1, 0, 0, 2, 2, 0, 2, 1, 0, 0, 0, 2, 1, 1, 1, 1, 1, 0, 2, 0, 0, 1,
       2, 1, 1, 2, 1, 1], dtype=int64)

In [18]:
db['h_clusterid']=hc.labels_
db

Unnamed: 0  Murder  Assault  UrbanPop  Rape  h_clusterid
0          Alabama    13.2      236        58  21.2            0
1           Alaska    10.0      263        48  44.5            0
2          Arizona     8.1      294        80  31.0            0
3         Arkansas     8.8      190        50  19.5            1
4       California     9.0      276        91  40.6            0
5         Colorado     7.9      204        78  38.7            0
6      Connecticut     3.3      110        77  11.1            1
7         Delaware     5.9      238        72  15.8            1
8          Florida    15.4      335        80  31.9            0
9          Georgia    17.4      211        60  25.8            0
10          Hawaii     5.3       46        83  20.2            1
11           Idaho     2.6      120        54  14.2            2
12        Illinois    10.4      249        83  24.0            0
13         Indiana     7.2      113        65  21.0            1
14            Iowa     2.2       56        57  11.3            2
15          Kansas     6.0      115        66  18.0            1
16        Kentucky     9.7      109        52  16.3            1
17       Louisiana    15.4      249        66  22.2            0
18           Maine     2.1       83        51   7.8            2
19        Maryland    11.3      300        67  27.8            0
20   Massachusetts     4.4      149        85  16.3            1
21        Michigan    12.1      255        74  35.1            0
22       Minnesota     2.7       72        66  14.9            1
23     Mississippi    16.1      259        44  17.1            0
24        Missouri     9.0      178        70  28.2            0
25         Montana     6.0      109        53  16.4            2
26        Nebraska     4.3      102        62  16.5            2
27          Nevada    12.2      252        81  46.0            0
28   New Hampshire     2.1       57        56   9.5            2
29      New Jersey     7.4      159        89  18.8            1
30      New Mexico    11.4      285        70  32.1            0
31        New York    11.1      254        86  26.1            0
32  North Carolina    13.0      337        45  16.1            0
33    North Dakota     0.8       45        44   7.3            2
34            Ohio     7.3      120        75  21.4            1
35        Oklahoma     6.6      151        68  20.0            1
36          Oregon     4.9      159        67  29.3            1
37    Pennsylvania     6.3      106        72  14.9            1
38    Rhode Island     3.4      174        87   8.3            1
39  South Carolina    14.4      279        48  22.5            0
40    South Dakota     3.8       86        45  12.8            2
41       Tennessee    13.2      188        59  26.9            0
42           Texas    12.7      201        80  25.5            0
43            Utah     3.2      120        80  22.9            1
44         Vermont     2.2       48        32  11.2            2
45        Virginia     8.5      156        63  20.7            1
46      Washington     4.0      145        73  26.2            1
47   West Virginia     5.7       81        39   9.3            2
48       Wisconsin     2.6       53        66  10.8            1
49         Wyoming     6.8      161        60  15.6            1

In [19]:
#by K_means
from sklearn.cluster import KMeans
from scipy.spatial.distance import cdist


In [20]:
db1=pd.read_csv('crime_data.csv')


In [21]:
def norm_func(i):
    x=(i-i.min())/(i.max()-i.min())
    return(x)

In [23]:
db_norm=norm_func(db.iloc[:,1:])

In [25]:
wcss=[]
for i in range(1,11):
    kmeans=KMeans(n_clusters=i)
    kmeans.fit(db_norm)
    wcss.append(kmeans.inertia_)
plt.plot(range(1,11),wcss)
plt.title('Elbow curv')
plt.xlabel('number of clusters')
plt.ylabel('WCSS')
plt.show()

C:\Users\Prajwal\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1036: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


In [26]:
model=KMeans(n_clusters=4)
model.fit(db_norm)
model.labels_

array([3, 1, 1, 0, 1, 1, 0, 0, 1, 3, 0, 2, 1, 0, 2, 0, 0, 3, 2, 1, 0, 1,
       0, 3, 1, 2, 2, 1, 2, 0, 1, 1, 3, 2, 0, 0, 0, 0, 0, 3, 2, 3, 1, 0,
       2, 0, 0, 2, 0, 0])

In [27]:
x=pd.Series(model.labels_)
db1['Clust']=x

In [28]:
db1.iloc[:,1:5].groupby(db1.Clust).mean()

Murder     Assault   UrbanPop       Rape
Clust                                             
0       5.715000  132.300000  70.800000  18.100000
1      10.815385  257.384615  76.000000  33.192308
2       3.180000   78.700000  49.300000  11.630000
3      14.671429  251.285714  54.285714  21.685714

In [29]:
# By DBSCAN method
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler

In [30]:
db3=pd.read_csv('crime_data.csv')

In [33]:
db=db3.iloc[:,1:5]

In [34]:
db.values

array([[ 13.2, 236. ,  58. ,  21.2],
       [ 10. , 263. ,  48. ,  44.5],
       [  8.1, 294. ,  80. ,  31. ],
       [  8.8, 190. ,  50. ,  19.5],
       [  9. , 276. ,  91. ,  40.6],
       [  7.9, 204. ,  78. ,  38.7],
       [  3.3, 110. ,  77. ,  11.1],
       [  5.9, 238. ,  72. ,  15.8],
       [ 15.4, 335. ,  80. ,  31.9],
       [ 17.4, 211. ,  60. ,  25.8],
       [  5.3,  46. ,  83. ,  20.2],
       [  2.6, 120. ,  54. ,  14.2],
       [ 10.4, 249. ,  83. ,  24. ],
       [  7.2, 113. ,  65. ,  21. ],
       [  2.2,  56. ,  57. ,  11.3],
       [  6. , 115. ,  66. ,  18. ],
       [  9.7, 109. ,  52. ,  16.3],
       [ 15.4, 249. ,  66. ,  22.2],
       [  2.1,  83. ,  51. ,   7.8],
       [ 11.3, 300. ,  67. ,  27.8],
       [  4.4, 149. ,  85. ,  16.3],
       [ 12.1, 255. ,  74. ,  35.1],
       [  2.7,  72. ,  66. ,  14.9],
       [ 16.1, 259. ,  44. ,  17.1],
       [  9. , 178. ,  70. ,  28.2],
       [  6. , 109. ,  53. ,  16.4],
       [  4.3, 102. ,  62. ,  16.5],
 